version: "3.0"
services:
  limesurvey:
    build:
      # Hint: Change it to 3.0/apache/ if you want to use LimeSurvey 3.*
      context: 5.0/apache/
      dockerfile: Dockerfile
    volumes:
      # Hint: This is just an example, change /tmp to something persistent
      - /tmp/upload/surveys:/var/www/html/upload/surveys
    links:
      - lime-db
    depends_on:
      - lime-db
    ports:
      # Hint: Change it to 80:8080 if you are using LimeSurvey 3.*
      - "8080:8080"
    environment:
      - "DB_TYPE=pgsql"
      - "DB_PORT=5432"
      - "DB_HOST=lime-db"
      - "DB_PASSWORD=secret"
      - "ADMIN_PASSWORD=foobar"
  lime-db:
    image: postgres:10
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      - "POSTGRES_USER=limesurvey"
      - "POSTGRES_DB=limesurvey"
      - "POSTGRES_PASSWORD=secret"

volumes:
  db-data:
